language: python

python:
  - "3.4"

cache: pip

before_install:
  - sudo apt-get -qq install ghostscript
  - sudo apt-get -qq install dvipng
  - sudo apt-get -qq install texlive-latex-extra
  - sudo apt-get -qq install texlive-fonts-recommended

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - r-base

install:
  - pip install -r test_requirements.txt
  - pip install -e .[rplot]

script: 
  - pytest

branches:
  only:
    - master
