language: python

python:
  - "3.5"

cache: pip

before_install:
  - sudo apt-get -qq install ghostscript
  - sudo apt-get -qq install dvipng
  - sudo apt-get -qq install texlive-latex-extra
  - sudo apt-get -qq install texlive-fonts-recommended
  - sudo apt-get -qq install samtools

before_script:
  - curl -L https://github.com/lh3/minimap2/releases/download/v2.10/minimap2-2.10_x64-linux.tar.bz2 | tar -jxvf -
  - export PATH=$PATH:$PWD/minimap2-2.10_x64-linux

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - r-base

install:
  - pip install -e .[rplot]

script: 
  - pytest

branches:
  only:
    - master
