language: python

python:
  - "3.6"

cache: pip

before_install:
  - sudo apt-get -qq install ghostscript
  - sudo apt-get -qq install dvipng
  - sudo apt-get -qq install texlive-latex-extra
  - sudo apt-get -qq install texlive-fonts-recommended
  - sudo apt-get -qq install samtools
  - sudo apt-get update
  - sudo apt-get upgrade
  # install minimap2
  - "wget https://github.com/lh3/minimap2/releases/download/v2.12/minimap2-2.12_x64-linux.tar.bz2"
  - "tar xvf minimap2-2.12_x64-linux.tar.bz2"
  - "export PATH=$PWD/minimap2-2.12_x64-linux:$PATH"

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - r-base

install:
  - pip install -e .[rplot]

# following here: https://stackoverflow.com/a/35403128
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - pytest

branches:
  only:
    - master
    - pacbio
