language: python
python:
  - "3.4"
cache: pip
install:
  - pip install -r test_requirements.txt
  - python setup.py build_ext --inplace
  - pip install .
script: 
  - pytest
branches:
  only:
    - master
